### PR TITLE
support laravel 8.0

### PR DESCRIPTION
**Pull request by CasperLaiTW**

### CODE REVIEW

**Comment by andreladocruz** [comment]
This is an important PR.

Can anyone, please approve and merge it, please?

**Comment by mous2890** [comment]
Second this!

**Comment by CasperLaiTW** [comment]
Before merge, guys, you can try my fork repo.

temporarily add my fork to the `repositories` property of your `composer.json`:
```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/CasperLaiTW/laravel-google-cloud-storage.git"
        }
    ]
}
```

then update your dependency constraint to reference this branch
```
{
    "require": {
        "superbalist/laravel-google-cloud-storage": "dev-master,
    }
}
```

**Review by Gummibeer — APPROVED** [review]

**Review by mous2890 — APPROVED** [review]

**Review by shahvirag — APPROVED** [review]

**Comment by mstaack** [comment]
@nicja you mind having a look at this PR?

**Comment by nicja** [comment]
> @nicja you mind having a look at this PR?

Unfortunately I am no longer an admin for this repo
@nikolaos-spyratos @bertuss can you help?

**Comment by BruinBear** [comment]
Can we have this merged? Thank you all :)

**Comment by sdwru** [comment]
> Before merge, guys, you can try my fork repo.
> 
> temporarily add my fork to the `repositories` property of your `composer.json`:
> 
> ```
> {
>     "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/CasperLaiTW/laravel-google-cloud-storage.git"
>         }
>     ]
> }
> ```
> 
> then update your dependency constraint to reference this branch
> 
> ```
> {
>     "require": {
>         "superbalist/laravel-google-cloud-storage": "dev-master,
>     }
> }
> ```

I'm waiting for an update to this package so I don't have to do that.

**Review by faytekin — APPROVED** [review]

**Comment by nikolaos-spyratos** [comment]
Hi all, apologies for the delay. Merged in and should be available for update already. We haven't tested on Laravel 8 specifically but I don't recall any big changes that would affect this simple package.

Nic is unfortunately no longer at Superbalist. Please tag me (@nikolaos-spyratos) or @bertuss in future 😄

**Pull request merged**
