### PR TITLE
Add Laravel 7 support.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR adds support for Laravel 7.

### CODE REVIEW

**Comment by mstaack** [comment]
perfect 👍

**Comment by litan1106** [comment]
nice

**Comment by mstaack** [comment]
@bertuss  please have a look and consider a new release please 😄

**Comment by mstaack** [comment]
@alihen do yo mind pushing a new release when you have time?

**Comment by timyboy12345** [comment]
I could also really use Laravel 7 support, if you have time, could you please commit this PR?

**Comment by HaxxanRaxa** [comment]
When can I use this package with Laravel 7?

**Comment by lucasmichot** [comment]
Hi @alihen - I guess you might pretty busy
Is there anything we can do to support this repository maybe?

Let me know if I can help, you can also DM me on Twitter: https://twitter.com/iamlucasmichot

**Comment by lucasmichot** [comment]
Or maybe @nicja ?

**Comment by lucasmichot** [comment]
Maybe @bertuss too?

**Comment by lbenevenuto** [comment]
Any one ?

**Comment by lucasmichot** [comment]
Thanks @nikolaos-spyratos 🙏

**Pull request merged**
