### PR TITLE
Support laravel 6.x

### PR DESCRIPTION
**Pull request by Mombuyish**

### CODE REVIEW

**Comment by litan1106** [comment]
Thanks for the PR

**Comment by Mombuyish** [comment]
I found some issues, laravel 5.8 or later doesn't support helper methods, so I'm instead of calling `Arr` class to use the compatible newer version.

**Comment by danielcommesse** [comment]
Is this still being worked on?

**Comment by garethnic** [comment]
Oki awesome.

**Comment by alexanderkraemer** [comment]
any updates here?

**Comment by Nks** [comment]
Can somebody approve the package? Only one package which still not updated to move forward.

**Comment by maherelgamil** [comment]
please approved this update :)

**Comment by smpetrey** [comment]
@AnsellC, @alexanderkraemer why hasn't this merged?

Regarding the issue @Mombuyish brought up:

> I found some issues, laravel 5.8 or later doesn't support helper methods, instead of calling Arr class to use the compatible newer version.

Bummer. However, [you can continue to use the helpers with this for Laravel 6.0 upgrades](https://laravel.com/docs/6.x/upgrade#helpers):

```
composer require laravel/helpers
```

So, if this package (`laravel-google-cloud-storage`) depends upon `larave/helpers`, I'm assuming we [can add it here to rectify that problem, right?](https://github.com/Superbalist/laravel-google-cloud-storage/blob/master/composer.json#L11)

Someone please correct me if I'm wrong.

**Comment by alexanderkraemer** [comment]
yes, but there might be a reason, the support was removed...
The pull-request fixes everything, and works. it just needs to be merged!

**Comment by AnsellC** [comment]
@smpetrey Im not a maintainer. Just "approved" it to get their attention or something. I'm also waiting, like the rest of you. For now you can just fork it then reference it on your `composer.json` file or use @Mombuyish's fork

**Comment by smpetrey** [comment]
@AnsellC that works for me until this PR gets merged! Thanks.

**Comment by bertuss** [comment]
Apologies for the slow response, the main maintainer is on sabbatical. I will merge and make a release shortly.

**Comment by garethnic** [comment]
@bertuss Dankie

**Comment by Nks** [comment]
Thanks @bertuss!

**Comment by smpetrey** [comment]
thanks @bertuss! 🙌

**Pull request merged**
